spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id // Google client id
            client-secret: client-secret // Google client secret
            scope:
              - email
          naver:
            client-id: client-id // Naver client id
            client-secret: client-secret // Naver client secret
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
