spring:
  profiles:
    include: oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/apple
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        default_batch_fetch_size: 100 # 컬렉션 패치 최적화
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 50MB
      location: /images/

file:
  upload-image-dir: "E:/upload"
  upload-thumbnail-dir: "E:/upload/thumbnail"


logging:
  level:
    root: info
    org.hibernate.sql: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
